version: '2'
services:
 db:
   image: postgres:9.6.1
   ports:
    - "54322:5432"
 rabbitmq:
   image: rabbitmq:3.6.5-management
   ports:
    - "15672:15672"
 api:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/code
   ports:
     - "8000:8000"
   depends_on:
     - db
     - rabbitmq
 worker:
   image: parcel_api:latest
   command: celery -A parcel worker -l info
   volumes:
     - .:/code
   depends_on:
     - api
 frontend:
   image: node:6.9.1
   command: bash -c "while true; do sleep 1; done"
   working_dir: /code/frontend
   volumes_from:
    - api
   depends_on:
    - api
 nginx:
   restart: always
   stdin_open: false
   image: nginx:latest
   ports:
    - "80:80"
   volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   volumes_from:
    - frontend
   depends_on:
    - frontend
